name: CI Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.5 
      - name: Set up Go module
        run: |
          cd src
          go mod init github.com/MohamedElashri/txm
          go get golang.org/x/crypto/ssh/terminal
          go mod tidy
      - name: Run Tests
        run: |
          cd src
          go test -v ./...
      - name: Build
        run: |
          go build -o txm-${{ matrix.os }}
          zip txm-${{ matrix.os }}.zip txm-${{ matrix.os }}
        working-directory: ./src