name: Comprehensive Test Suite

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  comprehensive-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22.5
      
      - name: Install system dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y tmux screen
            # Install zellij
            curl -L https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz | tar -xz
            sudo mv zellij /usr/local/bin/
          else
            # macOS
            brew install tmux screen
            # Install zellij
            brew install zellij
          fi
      
      - name: Set up Go module
        run: |
          cd src
          go get golang.org/x/term
          go mod tidy
      
      - name: Build txm
        run: |
          cd src
          go build -o txm
          chmod +x txm
      
      - name: Run unit tests
        run: |
          cd src
          go test -v
      
      - name: Test basic functionality
        run: |
          cd src
          # Test basic commands
          ./txm version
          # List command may fail if no sessions exist, but should not error
          ./txm list || echo "No sessions found (expected)"
      
      - name: Test configuration system
        run: |
          cd src
          # Test config commands
          ./txm config show
          
          # Test setting backends
          if command -v tmux >/dev/null 2>&1; then
            ./txm config set backend tmux
            echo "Backend set to tmux"
          fi
          
          if command -v zellij >/dev/null 2>&1; then
            ./txm config set backend zellij
            echo "Backend set to zellij"
          fi
          
          if command -v screen >/dev/null 2>&1; then
            ./txm config set backend screen
            echo "Backend set to screen"
          fi
          
          # Show final config
          ./txm config show
      
      - name: Test tmux backend (if available)
        if: success()
        run: |
          cd src
          if command -v tmux >/dev/null 2>&1; then
            echo "Testing tmux backend..."
            ./txm config set backend tmux
            
            # Test session operations - these should succeed
            echo "Creating tmux session..."
            ./txm create test-session-tmux
            
            echo "Listing sessions..."
            ./txm list
            
            echo "Creating window..."
            ./txm new-window test-session-tmux test-window
            
            echo "Listing windows..."
            ./txm list-windows test-session-tmux
            
            echo "Splitting window..."
            ./txm split-window test-session-tmux test-window v
            
            echo "Listing panes..."
            ./txm list-panes test-session-tmux test-window
            
            echo "Cleaning up tmux session..."
            ./txm delete test-session-tmux
          else
            echo "tmux not available, skipping tmux tests"
          fi
      
      - name: Test zellij backend (if available)
        if: success()
        run: |
          cd src
          if command -v zellij >/dev/null 2>&1; then
            echo "Testing zellij backend..."
            ./txm config set backend zellij
            
            # Test session operations - these should succeed
            echo "Creating zellij session..."
            ./txm create test-session-zellij
            
            echo "Listing sessions..."
            ./txm list
            
            echo "Creating tab..."
            ./txm new-window test-session-zellij test-tab
            
            echo "Listing tabs..."
            ./txm list-windows test-session-zellij || echo "List tabs not supported in zellij (expected)"
            
            echo "Splitting pane..."
            ./txm split-window test-session-zellij test-tab v || echo "Split pane failed (may need active session)"
            
            echo "Listing panes..."
            ./txm list-panes test-session-zellij test-tab || echo "List panes not supported in zellij (expected)"
            
            echo "Cleaning up zellij session..."
            ./txm delete test-session-zellij
          else
            echo "zellij not available, skipping zellij tests"
          fi
      
      - name: Test screen backend (if available)
        if: success()
        run: |
          cd src
          if command -v screen >/dev/null 2>&1; then
            echo "Testing screen backend..."
            ./txm config set backend screen
            
            # Test session operations - these should succeed
            echo "Creating screen session..."
            ./txm create test-session-screen
            
            echo "Listing sessions..."
            ./txm list
            
            echo "Creating window..."
            ./txm new-window test-session-screen test-window
            
            echo "Listing windows..."
            ./txm list-windows test-session-screen
            
            echo "Cleaning up screen session..."
            ./txm delete test-session-screen
          else
            echo "screen not available, skipping screen tests"
          fi
      
      - name: Test environment variable override
        run: |
          cd src
          # Test environment variable override
          if command -v tmux >/dev/null 2>&1; then
            TXM_DEFAULT_BACKEND=tmux ./txm config show
          fi
          
          if command -v zellij >/dev/null 2>&1; then
            TXM_DEFAULT_BACKEND=zellij ./txm config show
          fi
          
          if command -v screen >/dev/null 2>&1; then
            TXM_DEFAULT_BACKEND=screen ./txm config show
          fi
      
      - name: Test backend availability detection
        run: |
          cd src
          echo "Testing backend availability detection..."
          
          # Test with invalid backend - this should fail
          if ./txm config set backend invalid; then
            echo "ERROR: Invalid backend was accepted (should have failed)"
            exit 1
          else
            echo "Correctly rejected invalid backend"
          fi
          
          # Test fallback behavior
          ./txm config show
      
      - name: Test update command
        run: |
          cd src
          # Test update command - should handle development installation properly
          ./txm update
      
      - name: Test help and verbose modes
        run: |
          cd src
          # Test help command - should always work
          ./txm help || ./txm --help
          
          # Test verbose mode
          ./txm -v list || echo "No sessions in verbose mode"
          ./txm --verbose version
      
      - name: Cleanup test sessions
        if: always()
        run: |
          cd src
          # Clean up any remaining test sessions - this may fail if no sessions exist
          ./txm nuke || echo "No sessions to clean up"
      
      - name: Test installation script syntax
        run: |
          # Test that installation script is syntactically correct
          bash -n utils/install.sh
          bash -n utils/uninstall.sh
      
      - name: Archive binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: txm-${{ matrix.os }}
          path: src/txm