name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # sanad: ref=v7.0.0
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # sanad: ref=v7.0.0
        with:
          go-version: '1.26.0'
          
      - name: Set up Zig
        run: |
          ZIG_URL=$(curl -s https://ziglang.org/download/index.json | jq -r '.["0.15.2"]."x86_64-linux".tarball')
          cd /tmp
          wget $ZIG_URL -O zig.tar.xz
          tar xf zig.tar.xz
          DIR=$(ls -d zig-x86_64-linux-* | head -n 1)
          echo "/tmp/$DIR" >> $GITHUB_PATH
          
      - name: Download macOS SDK
        run: |
          cd /tmp
          wget https://github.com/joseluisq/macosx-sdks/releases/download/14.4/MacOSX14.4.sdk.tar.xz
          tar xf MacOSX14.4.sdk.tar.xz
          echo "MACOS_SDK_PATH=/tmp/MacOSX14.4.sdk" >> $GITHUB_ENV
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # sanad: ref=v7.2.2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
