name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    permissions:
      contents: write        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Go module
        run: |
          cd src
          go mod init github.com/MohamedElashri/txm
          go get golang.org/x/crypto/ssh/terminal
          go mod tidy
      - name: Build
        run: |
          go build -o txm-${{ runner.os }}
          zip txm-${{ runner.os }}.zip txm-${{ runner.os }}
        working-directory: ./src
      - name: Move artifacts
        run: mv src/txm-${{ runner.os }}.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: txm-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
